name: Backport merged pull request

on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    if: >
      (
        github.event.action == 'closed' &&
        github.event.pull_request.merged
      ) ||
      (
        github.event.action == 'labeled'
        && startsWith(github.event.label.name, 'backport')
        && github.event.pull_request.merged
      )
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.BACKPORT_APP_ID }}
          private-key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          # Token to authenticate requests to GitHub, ensures that created PRs run CI
          github_token: ${{ steps.generate-token.outputs.token }}
          branch_name: backport-#${pull_number}-to-${target_branch}
          pull_description: |
            ### This is an automated backport of #${pull_number} to branch `${target_branch}`.

            > [!CAUTION]
            > **Do not modify this pull request.**
            
            ${pull_description}
          pull_title: "${pull_title} [Backport #${pull_number} to ${target_branch}]"